### ISSUE TITLE
Category URL return 404 page

### ISSUE THREAD

**Issue by ghost** [ghosind/Jekyll-Paper#2]
What you do is really amazing, but I got a issue when fork and use
I don't know how to describe it so let me give you an example.
I have a category name **Talk**
The URL for Talk is **mydomain/category/talk** return 404 page
This just happened when i deploy on github page but it works perfectly locally

**Comment by ghosind** [comment]
Hi Phuc,

Thank you for your feedback, and I feel great honor that you like my project.

Jekyll Paper implement category page by 'jekyll-archives' plugin. However, GitHub Pages does not support this plugin. Unfortunately, I must tell you this project can not running at GitHub Pages.

In my another project ([Jekyll Paper Github](https://github.com/ghosind/Jekyll-Paper-Github)), I drop the 'jekyll-archives' plugin and implement category page in another way. You can try the [Jekyll Paper Github](https://github.com/ghosind/Jekyll-Paper-Github) project if you like Jekyll Paper's style.
